title: Brian Too CEAMLS SAIRI Website Summer 2024 
logo: assets/img/MYA03771.jpg 
description: Hi! My name is Brian Too and this is my CEAMLS SAIRI Website for Summer 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
